#github markdown rendering engine
markdown: kramdown
author:
  name: i05nagai
baseurl: /memorandum
#currrently github only supports minima
theme: minima
## following items are set by Gihutb io. We cannot override.
lsi: false
safe: true
incremental: false
# GFM style code highlight syntax
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
exclude: [application, aws, ci, browser, format, db, gpu, os, programming, shell, thesis, vim]
