# github markdown rendering engine
author: i05nagai
title: memo
baseurl: /memorandum
theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: book
    values:
      categories: [book]
  -
    scope:
      path: vim
    values:
      categories: [vim]
  -
    scope:
      path: ""
    values:
      layout: slate_page

# following items are set by Gihutb io. We cannot override.
lsi: false
safe: true
incremental: false
# GFM style code highlight syntax
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
markdown: kramdown
