#github markdown rendering engine
markdown: kramdown
author: i05nagai
baseurl: /memorandum
#currrently github only supports minima
theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: book
    values:
      categories: [book]
  -
    scope:
      path: ""
    values:
      layout: slate_page

## following items are set by Gihutb io. We cannot override.
lsi: false
safe: true
incremental: false
# GFM style code highlight syntax
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
exclude: [application, format, db, gpu, os, programming, shell, vim]
